ALTER TABLE TASK_EXECUTION MODIFY COLUMN END_TIME DATETIME(6) NULL;
ALTER TABLE TASK_EXECUTION MODIFY COLUMN START_TIME DATETIME(6) NULL;
ALTER TABLE TASK_EXECUTION MODIFY COLUMN LAST_UPDATED DATETIME(6) NULL;
ALTER TABLE TASK_LOCK MODIFY COLUMN CREATED_DATE DATETIME(6) NULL;
