ALTER TABLE TASK_EXECUTION ALTER COLUMN START_TIME SET DATA TYPE TIMESTAMP(9);
ALTER TABLE TASK_EXECUTION ALTER COLUMN END_TIME SET DATA TYPE TIMESTAMP(9);
ALTER TABLE TASK_EXECUTION ALTER COLUMN LAST_UPDATED SET DATA TYPE TIMESTAMP(9);
ALTER TABLE TASK_LOCK ALTER COLUMN CREATED_DATE SET DATA TYPE TIMESTAMP(9);

