= Spring Cloud Task image:https://build.spring.io/plugins/servlet/buildStatusImage/SCT-STASK[Build Status, link=https://build.spring.io/browse/SCT-STASK] image:https://badge.waffle.io/spring-cloud/spring-cloud-task.svg?label=ready&title=Ready[Stories in Ready, link=http://waffle.io/spring-cloud/spring-cloud-task] image:https://badge.waffle.io/spring-cloud/spring-cloud-task.svg?label=In%20Progress&title=In%20Progress[Stories in Progress, link=http://waffle.io/spring-cloud/spring-cloud-task]

Is a project centered around the idea of processing on demand.  A user is able to develop
a “task” that can be deployed, executed and removed on demand, yet the result of the
process persists beyond the life of the task for future reporting.


== Requirements:

* Java 7 or Above

== Build Main Project:

[source,shell,indent=2]
----
$ ./mvnw clean install
----

== Example:

[source,java,indent=2]
----
@SpringBootApplication
@EnableTask
public class MyApp {

	@Bean
	public MyTaskApplication myTask() {
		return new MyTaskApplication();
	}

	public static void main(String[] args) {
		SpringApplication.run(MyApp.class);
	}

	public static class MyTaskApplication implements CommandLineRunner {

		@Override
		public void run(String... strings) throws Exception {
			System.out.println("Hello World");
		}
	}
}
----

=== Sign the Contributor License Agreement
Before we accept a non-trivial patch or pull request we will need you to sign the
https://cla.pivotal.io/sign/spring[Contributor License Agreement].
Signing the contributor's agreement does not grant anyone commit rights to the main
repository, but it does mean that we can accept your contributions, and you will get an
author credit if we do.  Active contributors might be asked to join the core team, and
given the ability to merge pull requests.

== Code of Conduct
This project adheres to the Contributor Covenant link:CODE_OF_CONDUCT.adoc[code of conduct]. By participating, you  are expected to uphold this code. Please report unacceptable behavior to spring-code-of-conduct@pivotal.io.
