[[task-repository]]
= Spring Cloud Task Repository

[[partintro]]
--
Spring Cloud Task uses a relational database to store the results of an
executed task.  So when using a relational database, Spring Cloud Task will
create the tables necessary to store this information upon startup.  The
following section discusses some configuration options that are available
to allow you to customize this behavior.
--

[[task-repository-properties]]
== Task Repository Properties



=== Table Prefix
One modifiable property of the TaskRepository is the table prefix for the
task tables. By default they are all prefaced with `TASK_`.
TASK_EXECUTION and TASK_EXECUTION_PARAMS are two examples. However, there are
potential reasons to modify this prefix. If the schema names needs to be
prepended to the table names, or if more than one set of task tables is
needed within the same schema, then the table prefix will need to be changed.
This is done by setting the `spring.cloud.task.tablePrefix` to the prefix
that is required.

=== Enable/Disable table initialization
In cases where you are creating the task tables and do not wish for
Spring Cloud Task to create them (if not present) at task startup set the
`spring.cloud.task.initialize.enable` property to `false`.  It is currently
defaulted to `true`.
