[[preface]]
= Preface

[[task-documentation-about]]

This section provides a brief overview of the Spring Cloud Task reference documentation.
Think of it as a map for the rest of the document. You can read this reference guide in a
linear fashion or you can skip sections if something does not interest you.

[[about-the-documentation]]
== About the documentation
The Spring Cloud Task reference guide is available in {spring-cloud-task-docs}[html] 
and {spring-cloud-task-docs}/index.pdf[pdf]. The latest copy is available at
{spring-cloud-task-docs-current}.

Copies of this document may be made for your own use and for distribution to others,
provided that you do not charge any fee for such copies and further provided that each
copy contains this Copyright Notice, whether distributed in print or electronically.

[[task-documentation-getting-help]]
== Getting help
Having trouble with Spring Cloud Task? We would like to help!

* Ask a question. We monitor https://stackoverflow.com[stackoverflow.com] for questions
tagged with https://stackoverflow.com/tags/spring-cloud-task[`spring-cloud-task`].
* Report bugs with Spring Cloud Task at
https://github.com/spring-cloud/spring-cloud-task/issues.

NOTE: All of Spring Cloud Task is open source, including the documentation. If you find
a problem with the docs or if you just want to improve them, please {github-code}[get
involved].

[[task-documentation-first-steps]]
== First Steps
If you are just getting started with Spring Cloud Task or with 'Spring' in general, we
suggesting reading the xref:getting-started.adoc[Getting started] chapter.

To get started from scratch, read the following sections:

* xref:getting-started.adoc#getting-started-introducing-spring-cloud-task[Introducing Spring Cloud Task]
* xref:getting-started.adoc#getting-started-system-requirements[System Requirements] +

To follow the tutorial, read
xref:getting-started.adoc#getting-started-developing-first-task[Developing Your First Spring Cloud Task Application] +
To run your example, read
xref:getting-started.adoc#getting-started-running-the-example[Running the Example]
