= Spring Cloud Task

Is a project centered around the idea of processing on demand.  A user is able to develop
a “task” that can be deployed, executed and removed on demand, yet the result of the
process persists beyond the life of the task for future reporting.


== Requirements:

* Java 17 or Above

== Build Main Project:

[source,shell,indent=2]
----
$ ./mvnw clean install
----

== Example:

[source,java,indent=2]
----
@SpringBootApplication
@EnableTask
public class MyApp {

	@Bean
	public MyTaskApplication myTask() {
		return new MyTaskApplication();
	}

	public static void main(String[] args) {
		SpringApplication.run(MyApp.class);
	}

	public static class MyTaskApplication implements ApplicationRunner {

		@Override
		public void run(ApplicationArguments args) throws Exception {
			System.out.println("Hello World");
		}
	}
}
----

== Code of Conduct
This project adheres to the Contributor Covenant link:CODE_OF_CONDUCT.adoc[code of conduct]. By participating, you  are expected to uphold this code. Please report unacceptable behavior to spring-code-of-conduct@pivotal.io.

== Building the Project

This project requires that you invoke the Javadoc engine from the Maven command line. You can do so by appending `javadoc:aggregate` to the rest of your Maven command.
For example, to build the entire project, you could use `mvn clean install -DskipTests -P docs`.
